accelerator: gpu
devices: -1
strategy: ddp
max_epochs: 500
log_every_n_steps: 10
track_grad_norm: 2
gradient_clip_val: 1
gradient_clip_algorithm: norm
num_sanity_val_steps: 2
default_root_dir: ./pl_logs
