# General
experiment_name: classifier
checkpoints: ckpt_classifier/threshold0.7/
logs: logs
data: data
wandb_entity: qiao906187146
seed: 42
device: gpu

# Settings
sample_every_val: 1
log_every_steps: 50
samples_to_generate: 128
samples_to_save: 128
samples_per_input: 5
chains_to_save: 5
number_chain_steps_to_save: 50
enable_progress_bar: True

# Data
dataset: uspto50k
batch_size: 64
num_workers: 64
shuffle: True
extra_nodes: True
swap: False
use_positional_encoding: False
pos_enc_dim: 8

# Model
extra_features: all
extra_molecular_features: False
n_layers: 3
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}
hidden_dims: {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

# Training
n_epochs: 300
lambda_train: [5, 0]
lr: 0.0002
weight_decay: 0.000000000001


# loss coefficient
dec_loss: 0.4
cla_loss: 0.6
threshold: 0.9

enc_node_loss: 0.5
enc_edge_loss: 0.5
class_weights: [0.7,0.3]


# Checkpoint
resume:
