# General
experiment_name: retrebridge
checkpoints: checkpoints
logs: logs
data: data
wandb_entity: qiao906187146
seed: 42
device: gpu

# Settings
sample_every_val: 20
log_every_steps: 50
samples_to_generate: 128
samples_to_save: 128
samples_per_input: 5
chains_to_save: 5
number_chain_steps_to_save: 50
enable_progress_bar: True
visualization: False

# Data
dataset: uspto50k
batch_size: 64
num_workers: 6
shuffle: True
extra_nodes: True
swap: False

# Diffusion
diffusion_steps: 500
diffusion_noise_schedule: cosine
transition: null
fix_product_nodes: True

# Model
use_context: True
extra_features: all
extra_molecular_features: False
n_layers: 5
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}
hidden_dims: {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

#retrieval
retrieval_k: 1
embedding: rxn
augmented_graphfeature: False
retrieval_dataset: application # 50k or application
dropout: 0.1

# Training
n_epochs: 1000
lambda_train: [5, 0]
lr: 0.0002
weight_decay: 0.000000000001
loss_type: cross_entropy

# Checkpoint
resume:
